### ISSUE TITLE
[Korekto][TP1] première séance à compléter avant le 10/02/2020 23h00

### ISSUE THREAD

**Issue by ledoyen** [LouisQuentinCLAIN/mars-rover#7]
Votre exercice n'est pas complet :
* Badge Travis manquant dans le fichier [README.md](https://github.com/LouisQuentinCLAIN/mars-rover/blob/master/README.md) : [![Build Status](https://travis-ci.com/louisquentinclain/mars-rover.svg?branch=master)](https://travis-ci.com/louisquentinclain/mars-rover)

Rappel du sujet : https://github.com/ledoyen/tp-java/blob/master/projet/4A_2020/TP.md.  
Vous avez jusqu'au 10/02/2020 23h pour ajouter et/ou corriger ces erreurs.  
Au delà de cette date, la première séance de TP sera considérée incomplète et la note du projet sera réduite de 2 points.

**Comment by LouisQuentinCLAIN** [comment]
Badge ajouté au fichier README.md :

[![Build Status](https://travis-ci.com/LouisQuentinCLAIN/mars-rover.svg?branch=master)](https://travis-ci.com/LouisQuentinCLAIN/mars-rover)
